triggers:
- envs: []
  last_enabled_at: null
  name: prod
  pipeline_uuid: transform_load
  schedule_interval: '@daily'
  schedule_type: time
  settings: null
  sla: null
  start_time: 2024-03-30 15:00:00
  status: inactive
  variables: {}
