triggers:
- envs: []
  last_enabled_at: null
  name: get_latest
  pipeline_uuid: extract
  schedule_interval: '@daily'
  schedule_type: time
  settings:
    landing_time_enabled: true
  sla: null
  start_time: 2023-07-24 14:00:00
  status: inactive
  variables: {}
